version: 0.0
os: linux
files:
    - source: /
      destination: /var/www/typer-api/
hooks:
    BeforeInstall:
        - location: scripts/BeforeInstall.sh
    AfterInstall:
        - location: scripts/AfterInstall.sh
